conky.config = {
    alignment = 'top_right',
    background = false,
    border_width = 1,
    color1 = 'grey',
    color2 = 'lightgrey',
    color3 = 'white',
    color4 = 'green',
    color5 = 'red',
    cpu_avg_samples = 2,
    default_color = 'white',
    default_outline_color = 'white',
    default_shade_color = 'white',
    double_buffer = true,
    draw_borders = false,
    draw_graph_borders = true,
    draw_outline = false,
    draw_shades = false,
    extra_newline = false,
    font1 = 'PT Astra Fact:normal:size=10',
    font2 = 'PT Astra Fact:normal:size=9',
    gap_x = 20,
    gap_y = 20,
    minimum_height = 0,
    minimum_width = 0,
    net_avg_samples = 2,
    no_buffers = true,
    out_to_console = false,
    out_to_ncurses = false,
    out_to_stderr = false,
    out_to_x = true,
    own_window = true,
    own_window_argb_visual = false,
    own_window_colour = '585858',
    own_window_class = 'Conky',
    own_window_hints = 'undecorated,below,sticky,skip_taskbar,skip_pager',
    own_window_transparent = false,
    own_window_type = 'normal',
    show_graph_range = false,
    show_graph_scale = false,
    stippled_borders = 0,
    times_in_seconds = true,
    update_interval = 10.0,
    uppercase = false,
    use_spacer = 'none',
    use_xft = true
}

conky.text = [[
${font NotoSans:style=Bold:size=10}${alignc}${color3}- - Информация о системе - -
${font1}${color1}Операционная система: ${alignr}${font2}${color2}${execi 600 lsb_release -ds | awk '{print $1,$2}'} ${execi 600 cat /etc/astra/build_version}
${font1}${color1}Версия ядра: ${alignr}${font2}${color2}$kernel $machine
${font1}${color1}Уровень защищённости: ${alignr}${font2}${color2}${execi 600 cat /etc/astra_license | grep DESCRIPTION | awk -F '=' '{print $2}'}
${font1}${color1}МКЦ: ${alignr}${font2}${color2}${if_match ${execi 1800 cat /proc/cmdline | grep -i "parsec.max_ilev" | grep -i -v "parsec.max_ilev=0" | wc -l}>0}${exec echo "Включен"}${else}${exec echo "Отключен"}${endif}
${font1}${color1}Время работы: ${alignr}${font2}${color2}${format_time $uptime "\dд \hч \mм"}
${font1}${color1}Имя компьютера: ${alignr}${font2}${color2}$nodename_short
${font1}${color1}Имя домена: ${alignr}${font2}${color2}${execi 3600 hostname -d}
${hr 2}
${font NotoSans:style=Bold:size=10}${alignc}${color3}- - Информация о пользователях - -
${font1}${color1}Имя пользователя: ${alignr}${font2}${color2}$USER
${font1}${color1}Данные авторизации (kerberos): ${alignr}${font2}${color2}${execpi 600 klist -A -s && echo "\${color4}Актуальны" || echo "\${color5}Отсутствуют"}
${font1}${color1}Активных пользователей:${alignr}${font2}${color2}${execi 120 who | awk '{print $1}' | sort -u | wc -l}
${hr 2}
${font NotoSans:style=Bold:size=10}${alignc}${color3}- - Информация о сети - -
${font1}${color1}IP-адрес: ${alignr}${font2}${color2}${execi 60 ip addr show "$(ip route show default 2>/dev/null | awk '/default/ {print $5}' | head -1)" 2>/dev/null | grep -o "inet [0-9]\+\.[0-9]\+\.[0-9]\+\.[0-9]\+" | head -1 | awk '{print $2}'}
${font1}${color1}MAC-адрес: ${alignr}${font2}${color2}${execi 60 ip link show "$(ip route show default 2>/dev/null | awk '/default/ {print $5}' | head -1)" 2>/dev/null | grep -o "link/ether.*" | awk '{print $2}'}
${hr 2}
${font NotoSans:style=Bold:size=10}${alignc}${color3}- - Дисковое пространство - -
${font1}${color1}Корневой раздел: ${alignr}${font2}${color2}${fs_free /} / ${fs_size /}
${if_mounted /home}${font1}${color1}Домашний раздел: ${alignr}${font2}${color2}${fs_free /home} / ${fs_size /home}${endif}
${hr 2}
${font NotoSans:style=Bold:size=10}${alignc}${color3}- - Информация о ПО - -
${font1}${color1}Kaspersky: ${alignr}${font2}${color2}${if_match ${execpi 600 which kesl-control | wc -l}>0}${execp echo "Установлен"}${else}${exec echo "Не установлен"}${endif}
${font1}${color1}КриптоПРО: ${alignr}${font2}${color2}${execpi 600 /opt/cprocsp/bin/amd64/csptestf -keyset -verifycontext 2>/dev/null | sed -n 's/.* Ver:*\([0-9.]\+\).*/\1/p'}
]]

